import { plannerAgent } from "../agents/planner.agent.js";
import { coderAgent } from "../agents/coder.agent.js";
import { reviewerAgent } from "../agents/reviewer.agent.js";

console.log("Generator service loaded");

function fixAIFileTree(tree) {
  if (!tree || typeof tree !== 'object') {
    return {};
  }
  
  const result = {};
  
  const traverse = (node, path = '') => {
    if (node === null || node === undefined) return;
    
    // If node has contents, it's a file
    if (node.contents || node.file?.contents) {
      const content = node.contents || node.file?.contents || '';
      result[path || 'index.html'] = {
        file: {
          contents: typeof content === 'string' ? content : JSON.stringify(content, null, 2)
        }
      };
    }
    
    // If node is an object without contents, it's a directory
    else if (typeof node === 'object' && !Array.isArray(node)) {
      Object.keys(node).forEach(key => {
        const newPath = path ? `${path}/${key}` : key;
        traverse(node[key], newPath);
      });
    }
    
    // If node is a string, treat as file content
    else if (typeof node === 'string') {
      result[path || 'index.html'] = {
        file: {
          contents: node
        }
      };
    }
  };
  
  traverse(tree);
  return result;
}

export const generateProjectFileTree = async (prompt) => {
  try {
    console.log("🚀 Starting AI generation for prompt:", prompt);
    
    // 1️⃣ PLAN
    console.log("📋 Planning...");
    const plan = await plannerAgent(prompt);
    console.log("Plan generated:", plan);
    
    // 2️⃣ CODE
    console.log("💻 Coding...");
    const codedResult = await coderAgent(plan);
    console.log("Coded result:", Object.keys(codedResult));
    
    // 3️⃣ REVIEW
    console.log("🔍 Reviewing...");
    const reviewedResult = await reviewerAgent(codedResult.fileTree || codedResult);
    console.log("Reviewed result type:", typeof reviewedResult);
    
    // 4️⃣ FIX AND NORMALIZE
    console.log("🔧 Normalizing...");
    const normalizedFileTree = fixAIFileTree(reviewedResult);
    console.log("Normalized files:", Object.keys(normalizedFileTree));
    
    // Ensure at least basic files exist
    if (!normalizedFileTree['index.html'] && !normalizedFileTree['package.json']) {
      normalizedFileTree['index.html'] = {
        file: {
          contents: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${prompt.substring(0, 30)}...</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 20px;
      background: #f0f0f0;
    }
    h1 {
      color: #333;
    }
  </style>
</head>
<body>
  <h1>Project: ${prompt}</h1>
  <p>Generated by AI</p>
  <script>
    console.log('AI-generated project loaded');
  </script>
</body>
</html>`
        }
      };
    }
    
    return {
      plan,
      fileTree: normalizedFileTree
    };
    
  } catch (error) {
    console.error("❌ Error in generateProjectFileTree:", error);
    
    // Return fallback file tree
    return {
      plan: { error: error.message },
      fileTree: {
        'index.html': {
          file: {
            contents: `<!DOCTYPE html>
<html>
<head>
  <title>Error</title>
  <style>
    body { 
      font-family: Arial; 
      padding: 40px; 
      text-align: center; 
    }
    .error {
      color: red;
      background: #fee;
      padding: 20px;
      border-radius: 10px;
      margin: 20px auto;
      max-width: 600px;
    }
  </style>
</head>
<body>
  <h1>AI Generation Failed</h1>
  <div class="error">
    <p><strong>Error:</strong> ${error.message}</p>
    <p>Please try a different prompt or check the console.</p>
  </div>
</body>
</html>`
          }
        }
      }
    };
  }
};